# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Darcyctl < Formula
  desc "CLI for Darcy"
  homepage "https://meetdarcy.com"
  version "0.7.12"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/projectmin/homebrew-darcyctl/releases/download/v0.7.12/darcyctl-macos-amd64.tar.gz"
    sha256 "561bb67042c0367aeb28e2626b11b403e5658d7b553fb5f9e2c287bca3685211"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/projectmin/homebrew-darcyctl/releases/download/v0.7.12/darcyctl-linux-amd64.tar.gz"
    sha256 "e3ea362ed2155e39e4864a62a7f620bb30d74d2280a7dcae579d182353b44897"
  end

  def install
    bin.install "darcyctl"
  end

  test do
    system "#{bin}/darcyctl version"
  end
end
